// <auto-generated />
namespace Moodle.RealDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addAll : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addAll));
        
        string IMigrationMetadata.Id
        {
            get { return "201804121159253_addAll"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
